# Generated by Django 4.2.11 on 2024-05-13 19:00

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields
import phonenumber_field.modelfields
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '__first__'),
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='user', unique=True)),
                ('picture', models.ImageField(blank=True, default='default/default.png', null=True, upload_to=profiles.models.get_profile_pic_path)),
                ('bio', froala_editor.fields.FroalaField(blank=True, default="Hi there! Let's be friends", null=True, verbose_name='Bio')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='default/014.jpeg', null=True, upload_to=profiles.models.get_profile_cover_path)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address')),
                ('first_login', models.BooleanField(default=False)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date joined')),
                ('is_online', models.BooleanField(default=True, verbose_name='online')),
                ('is_active', models.BooleanField(default=True)),
                ('allow_anonymous', models.BooleanField(default=True)),
                ('private_mode', models.BooleanField(default=True)),
                ('hide_email', models.BooleanField(default=False)),
                ('blocked', models.ManyToManyField(blank=True, related_name='user_blocked', to=settings.AUTH_USER_MODEL)),
                ('chatted_with', models.ManyToManyField(blank=True, related_name='user_chatted_with', to=settings.AUTH_USER_MODEL)),
                ('saved_posts', models.ManyToManyField(blank=True, related_name='saved_posts', to='home.post')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('details', models.TextField(blank=True, max_length=500, null=True)),
                ('score', models.IntegerField(blank=True, default=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/skills')),
                ('is_key_skill', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default/014.jpeg', upload_to='profile/images')),
                ('thumbnail', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profilepic', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Potfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('details', froala_editor.fields.FroalaField(blank=True, null=True, verbose_name='Details')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/potfolio')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='potfolio', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Potfolio',
                'verbose_name_plural': 'Potfolios',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/files')),
                ('document', models.FileField(blank=True, null=True, upload_to='documents')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(blank=True, max_length=200, null=True)),
                ('qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('period', models.CharField(blank=True, max_length=30, null=True)),
                ('is_highest_level', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='AddressBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('default', models.BooleanField(default=True)),
                ('temp', models.BooleanField(default=False)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.area')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.country')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_book', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
