# Generated by Django 4.2.11 on 2024-05-14 23:45

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='default/default-avatar.png', null=True, upload_to=profiles.models.get_profile_pic_path),
        ),
    ]
