# Generated by Django 4.2.11 on 2024-05-26 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='saved_posts',
        ),
    ]
