# Generated by Django 4.2.11 on 2024-05-27 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_profile_saved_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='hide_email',
            new_name='hide_sensitive',
        ),
    ]
