# Generated by Django 4.2.11 on 2024-05-28 01:19

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_rename_hide_email_profile_hide_sensitive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default/014.jpeg', null=True, upload_to=profiles.models.get_profile_pic_path),
        ),
    ]
