# Generated by Django 4.2.11 on 2024-05-14 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the affiliate', max_length=255)),
                ('code', models.CharField(help_text='The unique code for the affiliate', max_length=255, unique=True)),
                ('description', models.TextField(help_text='A description of the affiliate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AffiliateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the affiliate link', max_length=255)),
                ('url', models.URLField(help_text='The URL of the affiliate link', max_length=2000)),
                ('clicks', models.IntegerField(default=0, help_text='The number of times the link has been clicked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affiliate', models.ForeignKey(help_text='The affiliate that the link is for', on_delete=django.db.models.deletion.CASCADE, to='affiliate.affiliate')),
                ('user', models.ForeignKey(help_text='The user that the affiliate is for', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
