# Generated by Django 4.2.11 on 2024-05-13 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=250)),
                ('line2', models.TextField()),
                ('line3', models.TextField()),
                ('banner', models.ImageField(upload_to='aboutus/banner')),
            ],
        ),
        migrations.CreateModel(
            name='Deepoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_1', models.ImageField(default=None, null=True, upload_to='deepoo')),
                ('logo_1_caption', models.CharField(blank=True, max_length=200, null=True)),
                ('logo_2', models.ImageField(default=None, null=True, upload_to='deepoo')),
                ('logo_2_caption', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-delimited set of SEO keywords for meta tag', max_length=255, null=True)),
                ('meta_description', models.CharField(blank=True, help_text='Content for description meta tag', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeepOracles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_1', models.ImageField(default=None, null=True, upload_to='deeporacles')),
                ('logo_1_caption', models.CharField(blank=True, max_length=200, null=True)),
                ('logo_2', models.ImageField(default=None, null=True, upload_to='deeporacles')),
                ('logo_2_caption', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-delimited set of SEO keywords for meta tag', max_length=255, null=True)),
                ('meta_description', models.CharField(blank=True, help_text='Content for description meta tag', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('job_title', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='aboutus/team/')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deepinfo.aboutus')),
            ],
        ),
        migrations.CreateModel(
            name='Admin_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('details', froala_editor.fields.FroalaField(blank=True, null=True, verbose_name='Details')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('receiver', models.ManyToManyField(related_name='admin_message_receivers', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
