# Generated by Django 4.2.11 on 2024-05-31 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deepinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'Aboutus'},
        ),
        migrations.AlterModelOptions(
            name='deeporacles',
            options={'verbose_name_plural': 'DeepOracles'},
        ),
    ]
