# Generated by Django 4.2.11 on 2024-05-13 19:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('drop_cap', models.CharField(blank=True, max_length=10, null=True)),
                ('highlight', models.TextField(blank=True, max_length=200, null=True, verbose_name='Highlight')),
                ('details', froala_editor.fields.FroalaField(blank=True, null=True, verbose_name='Details')),
                ('slug', models.SlugField(blank=True, max_length=150, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-delimited set of SEO keywords for meta tag', max_length=255, null=True)),
                ('meta_description', models.CharField(blank=True, help_text='Content for description meta tag', max_length=255, null=True)),
            ],
            options={
                'ordering': ('-date_posted',),
            },
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('drop_cap', models.CharField(blank=True, max_length=10, null=True)),
                ('highlight', models.TextField(blank=True, max_length=200, null=True, verbose_name='Highlight')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Brief Description')),
                ('details', froala_editor.fields.FroalaField(blank=True, null=True, verbose_name='Details')),
                ('slug', models.SlugField(blank=True, max_length=150, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-delimited set of SEO keywords for meta tag', max_length=255, null=True)),
                ('meta_description', models.CharField(blank=True, help_text='Content for description meta tag', max_length=255, null=True)),
            ],
            options={
                'ordering': ('-date_posted',),
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='noticeboard/info')),
                ('image_caption', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('details', froala_editor.fields.FroalaField(blank=True, null=True, verbose_name='Details')),
                ('highlight', models.TextField(blank=True, max_length=200, null=True, verbose_name='Highlight')),
                ('slug', models.SlugField(blank=True, max_length=150, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-delimited set of SEO keywords for meta tag', max_length=255, null=True)),
                ('meta_description', models.CharField(blank=True, help_text='Content for description meta tag', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='noticeboard/newscategory')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-delimited set of SEO keywords for meta tag', max_length=255, null=True)),
                ('meta_description', models.CharField(blank=True, help_text='Content for description meta tag', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('body', froala_editor.fields.FroalaField(blank=True, null=True, verbose_name='Body')),
                ('send_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Brief Description')),
                ('details', froala_editor.fields.FroalaField(blank=True, null=True, verbose_name='Details')),
                ('slug', models.SlugField(blank=True, max_length=150, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-delimited set of SEO keywords for meta tag', max_length=255, null=True)),
                ('meta_description', models.CharField(blank=True, help_text='Content for description meta tag', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyTips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('details', froala_editor.fields.FroalaField(blank=True, null=True, verbose_name='Details')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Brief Description')),
                ('details', froala_editor.fields.FroalaField(blank=True, null=True, verbose_name='Details')),
                ('slug', models.SlugField(blank=True, max_length=150, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-delimited set of SEO keywords for meta tag', max_length=255, null=True)),
                ('meta_description', models.CharField(blank=True, help_text='Content for description meta tag', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Startselling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('details', froala_editor.fields.FroalaField(blank=True, null=True, verbose_name='Details')),
                ('highlight', models.TextField(blank=True, max_length=200, null=True, verbose_name='Highlight')),
                ('active', models.BooleanField(default=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-delimited set of SEO keywords for meta tag', max_length=255, null=True)),
                ('meta_description', models.CharField(blank=True, help_text='Content for description meta tag', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Brief Description')),
                ('details', froala_editor.fields.FroalaField(blank=True, null=True, verbose_name='Details')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-delimited set of SEO keywords for meta tag', max_length=255, null=True)),
                ('meta_description', models.CharField(blank=True, help_text='Content for description meta tag', max_length=255, null=True)),
            ],
            options={
                'ordering': ('-date_posted',),
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='noticeboard/news')),
                ('image_caption', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('details', froala_editor.fields.FroalaField(blank=True, null=True, verbose_name='Details')),
                ('slug', models.SlugField(blank=True, max_length=150, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-delimited set of SEO keywords for meta tag', max_length=255, null=True)),
                ('meta_description', models.CharField(blank=True, help_text='Content for description meta tag', max_length=255, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infocategory', to='noticeboard.newscategory')),
            ],
            options={
                'ordering': ('-date_posted',),
            },
        ),
    ]
