# Generated by Django 4.2.11 on 2024-05-31 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={},
        ),
        migrations.AlterModelOptions(
            name='help',
            options={'verbose_name_plural': 'Help'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-date_posted',), 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='newscategory',
            options={'verbose_name_plural': 'NewsCategories'},
        ),
        migrations.AlterModelOptions(
            name='privacy',
            options={'verbose_name_plural': 'Privacies'},
        ),
        migrations.AlterModelOptions(
            name='safetytips',
            options={'verbose_name_plural': 'SafetyTips'},
        ),
        migrations.AlterModelOptions(
            name='security',
            options={'verbose_name_plural': 'Securities'},
        ),
        migrations.AlterModelOptions(
            name='terms',
            options={'verbose_name_plural': 'Terms'},
        ),
        migrations.RemoveField(
            model_name='faq',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='help',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='help',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='newscategory',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='newscategory',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='privacy',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='privacy',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='privacy',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='privacy',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='safetytips',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='safetytips',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='security',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='security',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='security',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='security',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='terms',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='terms',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='terms',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='terms',
            name='meta_keywords',
        ),
    ]
