# Generated by Django 4.2.11 on 2024-05-13 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('caption1', models.CharField(blank=True, max_length=500, null=True)),
                ('caption2', models.CharField(blank=True, max_length=500, null=True)),
                ('caption3', models.CharField(blank=True, max_length=500, null=True)),
                ('call_to_text', models.CharField(default='Shop Now', max_length=500)),
                ('call_to_url', models.CharField(default='/', max_length=500)),
                ('image', models.ImageField(upload_to='banner/')),
                ('banner_type', models.CharField(choices=[('banner1', 'banner1'), ('banner2', 'banner2'), ('banner3', 'banner3'), ('banner4', 'banner4'), ('banner5', 'banner5'), ('banner6', 'banner6'), ('banner4', 'banner7'), ('banner8', 'banner8')], default='Top', max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('symbol_native', models.CharField(max_length=5)),
                ('rate', models.FloatField(default=1)),
                ('decimal_digits', models.CharField(max_length=2)),
                ('code', models.CharField(max_length=10)),
                ('name_plural', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(max_length=200)),
                ('email_port', models.CharField(max_length=20)),
                ('email_use', models.CharField(max_length=10)),
                ('email_host_user', models.CharField(max_length=100)),
                ('email_host_password', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(blank=True, max_length=300, null=True)),
                ('subtitle1', models.CharField(blank=True, max_length=300, null=True)),
                ('icon1', models.CharField(blank=True, max_length=100, null=True)),
                ('title2', models.CharField(blank=True, max_length=300, null=True)),
                ('subtitle2', models.CharField(blank=True, max_length=300, null=True)),
                ('icon2', models.CharField(blank=True, max_length=100, null=True)),
                ('title3', models.CharField(blank=True, max_length=300, null=True)),
                ('subtitle3', models.CharField(blank=True, max_length=300, null=True)),
                ('icon3', models.CharField(blank=True, max_length=100, null=True)),
                ('title4', models.CharField(blank=True, max_length=300, null=True)),
                ('subtitle4', models.CharField(blank=True, max_length=300, null=True)),
                ('icon4', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('speed', models.IntegerField(default=3000)),
                ('autoplay', models.BooleanField(default=True)),
                ('autoplay_timeout', models.IntegerField(default=4000)),
                ('dots', models.BooleanField(default=True)),
                ('arrows', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Slider',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption_1', models.CharField(max_length=250, verbose_name='caption 1')),
                ('caption_2', models.CharField(max_length=250, verbose_name='caption 2')),
                ('caption_3', models.CharField(max_length=250, verbose_name='caption 3')),
                ('action_text', models.CharField(max_length=200, verbose_name='Call to Action Text')),
                ('action_url', models.URLField(verbose_name='Call to Action URL')),
                ('link_type', models.BooleanField(verbose_name='Open in new window')),
                ('image', models.ImageField(upload_to='slide/')),
                ('active', models.BooleanField(verbose_name='Status')),
                ('position', models.IntegerField(blank=True, null=True)),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide', to='settings.slider')),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Deep Oracles', max_length=255)),
                ('phone', models.CharField(blank=True, default=1, max_length=20, null=True)),
                ('logo', models.ImageField(default='default/Ajoreb.png', upload_to='settings/')),
                ('address', models.CharField(default='Kampala', max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('twitter', models.URLField(default='twitter.com')),
                ('facebook', models.URLField(default='facebook.com')),
                ('youtube', models.URLField(default='youtube.com')),
                ('instagram', models.URLField(default='instagram.com')),
                ('favicon', models.ImageField(default='default/Ajoreb.png', upload_to='settings/')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('banner1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='banner1', to='settings.banner')),
                ('banner2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='banner2', to='settings.banner')),
                ('banner3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='banner3', to='settings.banner')),
                ('banner4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='banner4', to='settings.banner')),
                ('banner5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='banner5', to='settings.banner')),
                ('banner6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='banner6', to='settings.banner')),
                ('banner7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='banner7', to='settings.banner')),
                ('banner8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='banner8', to='settings.banner')),
                ('privacy_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='privacy_policy', to='settings.pages')),
                ('slider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='settings.slider')),
                ('term_condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='term_condition', to='settings.pages')),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_email', models.BooleanField(default=True)),
                ('order_email', models.BooleanField(default=True)),
                ('order_status_email', models.BooleanField(default=True)),
                ('invoice_email', models.BooleanField(default=True)),
                ('default_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defailt_currency', to='settings.currency')),
                ('supported_currency', models.ManyToManyField(related_name='supported_currency', to='settings.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enable', models.BooleanField(default=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region', to='settings.country')),
            ],
        ),
        migrations.CreateModel(
            name='FooterLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('is_footer', models.BooleanField(default=False)),
                ('section_name', models.CharField(max_length=200)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('links', models.ManyToManyField(to='settings.links')),
            ],
        ),
        migrations.CreateModel(
            name='Conf_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('night_mode', models.BooleanField(choices=[(True, 'use dark theme'), (False, 'white-content')], default=True, max_length=10)),
                ('private_mode', models.BooleanField(choices=[(True, 'other contacts cannot add you to a conversation'), (False, 'other contacts can add you to a conversation')], default=False)),
                ('notifications', models.BooleanField(choices=[(True, 'receive notifications'), (False, 'never receive notifications')], default=True)),
                ('save_notifications', models.BooleanField(choices=[(True, 'save notifications'), (False, 'delete notifications')], default=False)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enable', models.BooleanField(default=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city', to='settings.region')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enable', models.BooleanField(default=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area', to='settings.city')),
            ],
        ),
    ]
