# Generated by Django 4.2.11 on 2024-05-14 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='favicon',
            field=models.ImageField(default='default/bitmagus.png', upload_to='settings/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='logo',
            field=models.ImageField(default='default/bitmagus.png', upload_to='settings/'),
        ),
    ]
