# Generated by Django 4.2.11 on 2024-05-28 08:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0003_rename_profile_conf_settings_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conf_Settings',
            new_name='Confsettings',
        ),
    ]
