# Generated by Django 4.2.11 on 2024-05-13 18:59

import autoslug.fields
import circles.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum_cover_photo', models.ImageField(blank=True, default='default/014.jpeg', null=True, upload_to=circles.models.get_forum_img_path)),
                ('forum_name', models.CharField(default='Forum', max_length=100)),
                ('picture', models.ImageField(blank=True, default='default/default-avatar.png', null=True, upload_to=circles.models.get_forum_img_path)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='forum_name', unique=True)),
                ('forum_bio', froala_editor.fields.FroalaField(blank=True, null=True, verbose_name='Forum Details')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('private_mode', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('date_hidden', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='forum_followers', to=settings.AUTH_USER_MODEL)),
                ('forum_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_author', to=settings.AUTH_USER_MODEL)),
                ('forum_members', models.ManyToManyField(blank=True, related_name='forum_members', to=settings.AUTH_USER_MODEL)),
                ('forum_members_blocked', models.ManyToManyField(blank=True, related_name='forum_blocked_members', to=settings.AUTH_USER_MODEL)),
                ('forum_members_waiting', models.ManyToManyField(blank=True, related_name='forum_waiting_members', to=settings.AUTH_USER_MODEL)),
                ('forum_sub_admin', models.ManyToManyField(blank=True, related_name='forum_sub_author', to=settings.AUTH_USER_MODEL)),
                ('hidden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_who_hid', to=settings.AUTH_USER_MODEL)),
                ('invite_forum_members', models.ManyToManyField(blank=True, related_name='invited_forum_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Circles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connections', models.ManyToManyField(blank=True, related_name='connections', to=settings.AUTH_USER_MODEL)),
                ('followers', models.ManyToManyField(blank=True, related_name='user_followers', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(blank=True, related_name='user_following', to=settings.AUTH_USER_MODEL)),
                ('forums', models.ManyToManyField(blank=True, related_name='user_forums', to='circles.forum')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='circles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
