# Generated by Django 4.2.11 on 2024-05-31 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circles',
            options={'verbose_name': 'Circle', 'verbose_name_plural': 'Circles'},
        ),
    ]
