# Generated by Django 4.2.11 on 2024-05-29 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_post_savedpost_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Audio_file',
            field=models.FileField(blank=True, null=True, upload_to='posts/audio_post_file', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['wav', 'aif', 'mp3', 'mid', '.opus', 'flac'])], verbose_name='audio'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Video_file',
            field=models.FileField(blank=True, null=True, upload_to='posts/video_post_file', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'wmv', 'mov', '3gp', 'flv', 'webm'])], verbose_name='video'),
        ),
    ]
