# Generated by Django 4.2.11 on 2024-05-28 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='verb',
        ),
    ]
