# Generated by Django 4.2.11 on 2024-06-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0002_remove_notification_verb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='text_preview',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
